image: alpine:latest

before_script:
- yarn install

pages:
  stage: deploy
  script:
  - npm run build
  # - cp -r build public
  # - cp public/index.html public/404.html
  # - find public -type f -iregex '.*\.\(js\)$' -execdir gzip -f {} \;
  # - cp -f build/*.js public/
  artifacts:
    paths:
    - build
  only:
  - master
